[package]
name = "linear_solver"
version = "0.1.0"
edition = "2018"
author = "neuring"

[profile.release]
overflow-checks = true

[dependencies]
anyhow = "1.0.45"
itertools = "0.10.1"
num = "0.4.0"
structopt = "0.3.25"
thiserror = "1.0.30"
